name: Publish JuniorPorfirio.CheckClauses to nuget
on:
  push:
    branches:
    - main
    paths: 
    - 'src/CheckClauses/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    # Publish
    - name: publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/CheckClauses/CheckClauses.csproj # Relative to repository root
        VERSION_REGEX: <Version>(.*)<\/Version> # Regex pattern to extract version info in a capturing group
        TAG_COMMIT: true # Flag to enable / disable git tagging
        TAG_FORMAT: GuardClauses-v* # Format of the git tag, [*] gets replaced with version
        NUGET_KEY: ${{secrets.NUGET_API_KEY}} 
