name: Publish CheckClauses to nuget
on:
  push:
    branches:
    - main
jobs:
  build-test-publish:
    name: publish to nuget
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.101
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test
      - name: Publish Nuget
        uses: brandedoutcast/publish-nuget@v2.5
        with: # All inputs are optional (details given below)
          PROJECT_FILE_PATH: src/CheckClauses/CheckClauses.csproj
          VERSION_REGEX: <Version>(.*)<\/Version>
          tag_format: v* # [*] gets replaced with version
          nuget_key: ${{secrets.NUGET_API_KEY}} # nuget.org API key
